# Generated by Django 5.2.6 on 2025-11-25 03:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coletor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nota_avaliacao_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_avaliacoes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'coletor',
            },
        ),
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cooperativa',
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nota_avaliacao_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('saldo_pontos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'produtor',
            },
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id_recompensa', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_voucher', models.CharField(max_length=50, unique=True)),
                ('nome_premio', models.CharField(max_length=100)),
                ('loja_parceira', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('RESGATADO', 'Resgatado')], max_length=20)),
                ('id_produtor', models.ForeignKey(db_column='id_produtor', on_delete=django.db.models.deletion.CASCADE, to='aplicativo_web.produtor')),
            ],
            options={
                'db_table': 'recompensa',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_coleta', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim_coleta', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ACEITA', 'Aceita'), ('CANCELADA', 'Cancelada'), ('CONFIRMADA', 'Confirmada'), ('AGUARDANDO', 'Aguardando'), ('CONCLUIDA', 'Concluída')], default='SOLICITADA', max_length=55)),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True)),
                ('coletor', models.ForeignKey(blank=True, db_column='coletor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas', to='aplicativo_web.coletor')),
                ('cooperativa', models.ForeignKey(blank=True, db_column='cooperativa_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='aplicativo_web.cooperativa')),
                ('produtor', models.ForeignKey(db_column='produtor_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='aplicativo_web.produtor')),
            ],
            options={
                'db_table': 'solicitacao_coleta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemColeta',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tipo_residuo', models.CharField(choices=[('Vidro', 'Vidro'), ('Metal', 'Metal'), ('Papel', 'Papel'), ('Plástico', 'Plástico')], default='Plástico', max_length=50)),
                ('unidade_medida', models.CharField(choices=[('KG', 'KG'), ('UN', 'UN'), ('VOLUME', 'VOLUME')], default='UN', max_length=10)),
                ('solicitacao', models.ForeignKey(db_column='id_solicitacao', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='aplicativo_web.solicitacaocoleta')),
            ],
            options={
                'db_table': 'item_solicitacao',
            },
        ),
        migrations.CreateModel(
            name='CooperativaMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_residuo', models.CharField(choices=[('Plástico', 'Plástico'), ('Papel', 'Papel'), ('Metal', 'Metal'), ('Vidro', 'Vidro')], max_length=50)),
                ('preco_oferecido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cooperativa', models.ForeignKey(db_column='cooperativa_id', on_delete=django.db.models.deletion.CASCADE, to='aplicativo_web.cooperativa')),
            ],
            options={
                'db_table': 'cooperativa_material',
                'unique_together': {('cooperativa', 'tipo_residuo')},
            },
        ),
    ]
